- name: check a number less thab 10 or not
  hosts: localhost
  connection: local
  vars:
    NUMBER_OF_SESSIONS: 7
  tasks:
  - name: is ansible is less than 10
    ansible.builtin.debug:
      msg:  "yes ansible is less than 10"
    when: NUMBER_OF_SESSIONS >5 
  