- name: filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible
    tagsmap: 
      name: ansible
      project: roboshop
      component: with aws
    tagslist: [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "component",
            "value": "with aws"
        }
    ]
  tasks:
  - name: greeting
    ansible.builtin.debug:
     msg: "Hello Harshavardhan, {{ Greeting | default('Good Morning') }}"
  - name: convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"
  - name: map to list
    ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"
  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tags | items2dict }}"