[frontend]
192.78.98.45
192.78.98.46
192.78.98.47

[backend]
192.78.98.45
192.78.98.46
192.78.98.47

[roboshop:children]
frontend
backend

[web]
localhost ansible_connection=local

[ansible]
172.31.2.48

[local]
localhost

[local:vars]
COURSE="Ansible from inventory"
NAME="Ansible from inventory"