- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: instal three packages in loop
    ansible.builtin.package:
    name: "{{ item }}"
    state: present
    loop:
     - mysql
     - nginx 
      - msmtp
  - name: print success message
    ansible.builtin.debug:
       msg: "Installed packages completed"