- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: check nginx status
    ansible.builtin.command: systemctl status nginx
    register: nginx_status
  - name: print nginx status
    ansible.builtin.debug:
      msg: "{{ nginx_status }}"