- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: stop nginx
    ansible.builtin.service:
      name: nginx
      state: stopped
      enabled: no
  - name: uninstall nginx package
    ansible.builtin.dnf:
      name: nginx
      state: absent