- name: Typing the file
  hosts: localhost
  connection: local
  vars:
     COURSE: "Devops with Everything"
     DURATION: "4 months"
     TRAINER: "MYSELF"
  tasks:
  - name: print variables
    ansible.builtin.debug:
    msg: "Course is: {{ COURSE }}, Duration is: {{ DURATION }}, Trainer is: {{ TRAINER }}"